version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt_inst_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads  # Локальная папка для загрузок
    ports:
      - "8080:8080"  # Если понадобится внешний доступ (напр. healthcheck)
