version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_downloader
    restart: unless-stopped
    network_mode: host # Используем сеть хоста для контейнера
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN} # Переменная окружения для токена
